/**
 * The hash containers and the binary IO the clip cache is built on.
 *
 * `IdSet` / `IdMap` are checked against the JavaScript `Set` and `Map` they replace, which
 * makes the built-ins the oracle: an independent implementation rather than a restatement of
 * this one. `ByteWriter` / `ByteReader` are checked at the value boundaries where a
 * shift-based varint silently wraps, because that is the bug class already found once in the
 * PBF reader and the same reasoning applies here.
 *
 * Ids are generated by a fixed LCG rather than Math.random, so a failure is reproducible
 * instead of appearing once in CI and never again.
 */
import { describe, expect, it } from 'vitest';
import { IdMap, IdSet } from '../../packages/pipeline/clip/idset.ts';
import { ByteReader, ByteWriter } from '../../packages/pipeline/clip/binio.ts';

/** Deterministic ids spanning past 2^32, the way real OSM ids do. */
function* lcgIds(count: number, seed = 12345): Generator<number> {
  let s = seed;
  for (let i = 0; i < count; i++) {
    s = (Math.imul(s, 1103515245) + 12345) >>> 0;
    // Spread into the 1e9 to 1.4e10 range that real OSM node ids occupy.
    yield 1 + s * 3 + (i % 7);
  }
}

describe('IdSet', () => {
  it('agrees with a native Set on membership across many large ids', () => {
    const set = new IdSet(64);
    const ref = new Set<number>();
    // Mismatches are accumulated and asserted once. An expect() per iteration costs tens of
    // microseconds, which turns 20,000 ids into seconds, and this folder's tests must stay
    // instant so nobody is tempted to skip them.
    let newnessDisagreements = 0;
    for (const id of lcgIds(20_000)) {
      if (set.add(id) !== !ref.has(id)) newnessDisagreements++;
      ref.add(id);
    }
    let missing = 0;
    for (const id of ref) if (!set.has(id)) missing++;
    expect(newnessDisagreements).toBe(0);
    expect(missing).toBe(0);
    expect(set.size).toBe(ref.size);
  });

  it('reports absence for ids never added', () => {
    const set = new IdSet(16);
    for (const id of lcgIds(500)) set.add(id);
    // Deliberately outside the generated range, so these are genuinely absent.
    for (let id = 2; id < 500; id++) {
      if (!set.has(id)) continue;
      throw new Error(`id ${id} should not be present`);
    }
    expect(set.has(1)).toBe(false);
  });

  it('grows past its initial capacity without losing entries', () => {
    const set = new IdSet(16);
    const ids = [...lcgIds(5_000)];
    for (const id of ids) set.add(id);
    expect(set.capacity).toBeGreaterThan(5_000);
    for (const id of ids) expect(set.has(id)).toBe(true);
  });

  it('refuses id 0, which is the empty sentinel', () => {
    // Storing 0 would occupy a slot that reads back as empty, so every later probe through
    // that slot would terminate early and report false for ids that are present.
    expect(() => new IdSet().add(0)).toThrow(/sentinel/);
  });

  it('detects a duplicate id, which is what the seam dedupe depends on', () => {
    const set = new IdSet();
    expect(set.add(1_234_567_890_123)).toBe(true);
    expect(set.add(1_234_567_890_123)).toBe(false);
    expect(set.size).toBe(1);
  });
});

describe('IdMap', () => {
  it('agrees with a native Map, keeping the FIRST value written', () => {
    const map = new IdMap(64);
    const ref = new Map<number, number>();
    let newnessDisagreements = 0;
    let i = 0;
    for (const id of lcgIds(20_000)) {
      if (map.set(id, i) !== !ref.has(id)) newnessDisagreements++;
      if (!ref.has(id)) ref.set(id, i);
      i++;
    }
    let wrongValues = 0;
    for (const [id, v] of ref) if (map.get(id) !== v) wrongValues++;
    expect(newnessDisagreements).toBe(0);
    expect(wrongValues).toBe(0);
    expect(map.size).toBe(ref.size);
  });

  it('first-write-wins is the dedupe policy, not last-write-wins', () => {
    const map = new IdMap();
    map.set(999_999_999_999, 7);
    expect(map.set(999_999_999_999, 42)).toBe(false);
    expect(map.get(999_999_999_999)).toBe(7);
  });

  it('returns -1 for an absent id', () => {
    const map = new IdMap();
    map.set(5, 0);
    expect(map.get(6)).toBe(-1);
    expect(map.has(6)).toBe(false);
    // Index 0 is a legitimate value and must not be confused with absence.
    expect(map.has(5)).toBe(true);
    expect(map.get(5)).toBe(0);
  });

  it('refuses a negative value, because -1 means absent', () => {
    expect(() => new IdMap().set(5, -1)).toThrow(/negative/);
  });
});

describe('ByteWriter and ByteReader', () => {
  const CASES = [0, 1, 127, 128, 129, 255, 256, 16_383, 16_384, 2 ** 31 - 1, 2 ** 31, 2 ** 32, 2 ** 40, 13_000_000_000, 2 ** 53 - 1];

  it('round-trips varints across every boundary where a 32-bit shift would wrap', () => {
    const w = new ByteWriter(8);
    for (const v of CASES) w.varint(v);
    const r = new ByteReader(w.view());
    for (const v of CASES) expect(r.varint()).toBe(v);
    expect(r.hasMore).toBe(false);
  });

  it('round-trips zigzag varints including negatives', () => {
    // Zigzag DOUBLES the magnitude, so the exact range for svarint is half the varint range.
    // 2^52-1 is the largest safe input, and the case list stops there deliberately: the two
    // limits are different and conflating them is how a silent truncation gets introduced.
    const ZIGZAG_SAFE = CASES.filter((v) => v <= 2 ** 52 - 1);
    // 0 is excluded from the negated half: negating it yields -0, which reads back as +0.
    // That is numerically correct and only fails Object.is, so asserting it would be testing
    // JavaScript's signed zero rather than this encoder.
    const vals = [
      ...ZIGZAG_SAFE.filter((v) => v !== 0).map((v) => -v),
      ...ZIGZAG_SAFE,
      2 ** 52 - 1,
      -(2 ** 52 - 1),
    ];
    const w = new ByteWriter(8);
    for (const v of vals) w.svarint(v);
    const r = new ByteReader(w.view());
    for (const v of vals) expect(r.svarint()).toBe(v);
  });

  it('refuses an svarint whose zigzag would pass 2^53-1', () => {
    // Real inputs here are node id deltas and scaled coordinates, both far inside this, so
    // the limit costs nothing. It is asserted so the halved range stays documented in code
    // rather than being rediscovered by a wrong value much later.
    expect(() => new ByteWriter().svarint(2 ** 53 - 1)).toThrow(/2\^53/);
    expect(() => new ByteWriter().svarint(-(2 ** 53 - 1))).toThrow(/2\^53/);
  });

  it('refuses values it cannot round-trip exactly, rather than truncating them', () => {
    // Silent truncation is the failure mode being designed out: it produces a plausible
    // wrong id instead of an error, and nothing downstream can tell the difference.
    expect(() => new ByteWriter().varint(2 ** 53)).toThrow(/2\^53/);
    expect(() => new ByteWriter().varint(-1)).toThrow(/non-negative/);
    expect(() => new ByteWriter().varint(1.5)).toThrow(/integer/);
  });

  it('round-trips negative and extreme i32 values', () => {
    const vals = [0, 1, -1, 127, -128, 2 ** 31 - 1, -(2 ** 31), 289_000_000, -777_684_780];
    const w = new ByteWriter(8);
    for (const v of vals) w.i32(v);
    const r = new ByteReader(w.view());
    // Scaled coordinates are stored as i32, and a lost sign puts the city in the wrong
    // hemisphere while still looking like a valid number.
    for (const v of vals) expect(r.i32()).toBe(v);
  });

  it('round-trips Devanagari and Arabic script exactly', () => {
    const vals = ['कासना', 'नई दिल्ली', 'دریائے راوی', 'Pari Chowk', '', 'a/b|c'];
    const w = new ByteWriter(8);
    for (const v of vals) w.string(v);
    const r = new ByteReader(w.view());
    // Root CLAUDE.md: the Windows default text codec mangles this and it has already bitten
    // once. Explicit UTF-8 both ways is what this asserts.
    for (const v of vals) expect(r.string()).toBe(v);
  });

  it('throws rather than reading past the end', () => {
    const w = new ByteWriter(8);
    w.varint(300);
    const r = new ByteReader(w.view());
    r.varint();
    expect(() => r.varint()).toThrow(/past end|runs past/);
  });

  it('keeps the cursor aligned across mixed field types', () => {
    const w = new ByteWriter(8);
    w.varint(13_000_000_000);
    w.string('कासना');
    w.i32(-289_000_000);
    w.svarint(-98_765_432_101);
    w.u8(7);
    w.varint(1);
    const r = new ByteReader(w.view());
    expect(r.varint()).toBe(13_000_000_000);
    expect(r.string()).toBe('कासना');
    expect(r.i32()).toBe(-289_000_000);
    expect(r.svarint()).toBe(-98_765_432_101);
    expect(r.u8()).toBe(7);
    // The last value is the alignment check: any earlier off-by-N shows up here, which is the
    // shape that caught the PBF skip desync.
    expect(r.varint()).toBe(1);
    expect(r.hasMore).toBe(false);
  });
});
